module Helpers
  module Genius
    module Track
      class << self
        def description_data
          {:track=>{:description=>"“Running Up That Hill (A Deal With God)” is the first single from Kate Bush’s 1985 LP Hounds of Love.  “A Deal With God” was the song’s original title; it was changed at the insistence of EMI’s marketing department.\n\nBush wrote it about “if (men and women) could actually swap each other’s roles … it would lead to a greater understanding.”\n\nThe single was released on August 5th, 1985 in advance of the album’s September release.  The b-side of the original single release was “Under the Ivy”.\n\nThe song reached No. 3 in the UK charts, No.6 in the Australian Charts and No. 30 on the US Billboard Hot 100; in the US it remains Bush’s first and only major charting success."}}
        end

        def info_data
          {:track=>{:album=>{:title=>"Hounds of Love"}, :albums=>[{:genius_id=>46065, :title=>"Hounds of Love"}, {:genius_id=>154442, :title=>"Chilled Electronic 80s"}, {:genius_id=>331230, :title=>"The Whole Story"}, {:genius_id=>375677, :title=>"NOW That’s What I Call Music 6 [UK]"}], :artist=>{:name=>"Kate Bush"}, :artists=>[{:genius_id=>39200, :name=>"Kate Bush"}], :description=>"“Running Up That Hill (A Deal With God)” is the first single from Kate Bush’s 1985 LP Hounds of Love.  “A Deal With God” was the song’s original title; it was changed at the insistence of EMI’s marketing department.\n\nBush wrote it about “if (men and women) could actually swap each other’s roles … it would lead to a greater understanding.”\n\nThe single was released on August 5th, 1985 in advance ...", :genius_id=>344944, :image=>{:extrasmall=>"https://t2.genius.com/unsafe/50x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :large=>"https://t2.genius.com/unsafe/600x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :medium=>"https://t2.genius.com/unsafe/300x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :original=>"https://t2.genius.com/unsafe/1000x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :small=>"https://t2.genius.com/unsafe/100x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png"}, :lyrics=>"[Verse 1]\nIt doesn't hurt me\nDo you want to feel how it feels?\nDo you want to know, know that it doesn't hurt me?\nDo you want to hear about the deal that I'm making?\n\n[Pre-Chorus 1]\nYou\nIt's you and me\n\n[Chorus]\nAnd if I only could\nI'd make a deal...", :release_date=>"05 Aug 1985", :tags=>[{:name=>"Adult Alternative"}, {:name=>"Brit Pop"}, {:name=>"Eighties"}, {:name=>"British Rock"}, {:name=>"UK"}], :player_id=>"1", :title=>"Running Up That Hill (A Deal with God)", :with_more=>{:description=>true, :tags=>true}}}
        end

        def lyrics_data
          {:track=>{:lyrics=>"[Verse 1]\nIt doesn't hurt me\nDo you want to feel how it feels?\nDo you want to know, know that it doesn't hurt me?\nDo you want to hear about the deal that I'm making?\n\n[Pre-Chorus 1]\nYou\nIt's you and me\n\n[Chorus]\nAnd if I only could\nI'd make a deal with God\nAnd I'd get him to swap our places\nBe running up that road\nBe running up that hill\nBe running up that building\nSay, if I only could, oh...\n\n[Verse 2]\nYou don't want to hurt me\nBut see how deep the bullet lies\nUnaware I'm tearing you asunder\nOoh, there is thunder in our hearts\nIs there so much hate for the ones we love?\nTell me, we both matter, don't we?\n[Pre-Chorus 2]\nYou\nIt's you and me\nIt's you and me, won't be unhappy\n\n[Chorus]\nAnd if I only could\nI'd make a deal with God\nAnd I'd get him to swap our places\nBe running up that road\nBe running up that hill\nBe running up that building\nSay, if I only could, oh...\n\n[Pre-Chorus 2]\nYou\nIt's you and me\nIt's you and me, won't be unhappy\n\n[Bridge]\nOh come on, baby\nOh come on, darling\nLet me steal this moment from you now\nOh come on, angel\nCome on, come on, darling\nLet's exchange the experience, oh\n[Chorus 2]\nAnd if I only could\nI'd make a deal with God\nAnd I'd get him to swap our places\nI'd be running up that road\nBe running up that hill\nWith no problems\n\n[Chorus 2]\nSay, if I only could\nI'd make a deal with God\nAnd I'd get him to swap our places\nI'd be running up that road\nBe running up that hill\nWith no problems\n\n[Chorus 2]\nSay, if I only could\nI'd make a deal with God\nAnd I'd get him to swap our places\nI'd be running up that road\nBe running up that hill\nWith no problems\n\n[Outro]\nSay, if I only could\nBe running up that hill\nWith no problems\nIf I only could, be running up that hill\nIf I only could, be running up that hill"}}
        end

        def tags_data
          {:track=>{:tags=>[{:name=>"Adult Alternative"}, {:name=>"Brit Pop"}, {:name=>"Eighties"}, {:name=>"British Rock"}, {:name=>"UK"}, {:name=>"Rock"}, {:name=>"Synth-Pop"}, {:name=>"Pop"}, {:name=>"New Wave"}, {:name=>"Art Pop"}]}}
        end
      end
    end
  end
end
