module Helpers
  module Genius
    module Track
      class << self
        def description_data
          {:track=>{:description=>"“Running Up That Hill (A Deal With God)” is the first single from Kate Bush’s 1985 LP Hounds of Love.  “A Deal With God” was the song’s original title; it was changed at the insistence of EMI’s marketing department.\n\nBush wrote it about “if (men and women) could actually swap each other’s roles … it would lead to a greater understanding.”\n\nThe single was released on August 5th, 1985 in advance of the album’s September release.  The b-side of the original single release was “Under the Ivy”.\n\nThe song reached No. 3 in the UK charts, No.6 in the Australian Charts and No. 30 on the US Billboard Hot 100; in the US it remains Bush’s first and only major charting success."}}
        end

        def info_data
          {:track=>{:album=>{:source=>{:id=>46065, :name=>"genius"}, :title=>"Hounds of Love"}, :artist=>{:name=>"Kate Bush"}, :artists=>[{:name=>"Kate Bush", :source=>{:id=>39200, :name=>"genius"}}], :description=>"“Running Up That Hill (A Deal With God)” is the first single from Kate Bush’s 1985 LP Hounds of Love.  The song’s original title, “A Deal With God”, was changed at the insistence of EMI’s marketing department to be more palatable to religious countries.\n\nThe single was released on August 5th, 1985, a month before the album’s release. The song originally peaked at No. 3 on the UK charts, No. 6 o...", :image=>{:extrasmall=>"https://t2.genius.com/unsafe/50x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :large=>"https://t2.genius.com/unsafe/600x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :medium=>"https://t2.genius.com/unsafe/300x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :original=>"https://t2.genius.com/unsafe/1000x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png", :small=>"https://t2.genius.com/unsafe/100x0/https://images.genius.com/2c878c1ab0691000f2bc1ff7010402b7.966x966x1.png"}, :lyrics=>"[Verse 1]\nIt doesn't hurt me (Yeah, yeah, yo)\nDo you wanna feel how it feels? (Yeah, yeah, yo)\nDo you wanna know, know that it doesn't hurt me? (Yeah, yeah, yo)\nDo you wanna hear about the deal tha...", :player_id=>"1", :release_date=>"1985-08-05", :source=>{:id=>344944, :name=>"genius"}, :tags=>[{:name=>"UK Pop"}, {:name=>"Netflix"}, {:name=>"TV"}, {:name=>"Avant Garde"}, {:name=>"Art Rock"}], :title=>"Running Up That Hill (A Deal with God)", :with_more=>{:description=>true, :tags=>true}}}
        end

        def lyrics_data
          {:track=>{:lyrics=>["[Verse 1]", "\n", {:annotation_id=>2970345, :text=>["It doesn't hurt me (Yeah, yeah, yo)", "\n", "Do you wanna feel how it feels? (Yeah, yeah, yo)", "\n", "Do you wanna know, know that it doesn't hurt me? (Yeah, yeah, yo)", "\n", "Do you wanna hear about the deal that I'm makin'? (Yeah, yeah, yo)"]}, "\n", "\n", "[Pre-Chorus]", "\n", "You", "\n", "It's you and me", "\n", "\n", "[Chorus]", "\n", {:annotation_id=>2970368, :text=>["And if I only could", "\n", "I'd make a deal with God", "\n", "And I'd get him to swap our places", "\n", "Be runnin' up that road", "\n", "Be runnin' up that hill", "\n", "Be runnin' up that buildin'", "\n", "Say, if I only could, oh"]}, "\n", "[Verse 2]", "\n", {:annotation_id=>2970345, :text=>["You don't wanna hurt me (Yeah, yeah, yo)", "\n", "But see how deep the bullet lies (Yeah, yeah, yo)", "\n", "Unaware, I'm tearin' you asunder (Yeah, yeah, yo)", "\n", "Oh, there is thunder in our hearts (Yeah, yeah, yo)", "\n", "Is there so much hate for the ones we love? (Yeah, yeah, yo)", "\n", "Oh, tell me, we both matter, don't we? (Yeah, yeah, yo)"]}, "\n", "\n", "[Pre-Chorus]", "\n", "You", "\n", "It's you and me", "\n", "It's you and me, won't be unhappy", "\n", "\n", "[Chorus]", "\n", {:annotation_id=>2970368, :text=>["And if I only could", "\n", "I'd make a deal with God", "\n", "And I'd get him to swap our places", "\n", "Be runnin' up that road", "\n", "Be runnin' up that hill", "\n", "Be runnin' up that buildin' (Yo)", "\n", "Say, if I only could, oh"]}, "\n", "\n", "[Post-Chorus]", "\n", "You (Yeah, yeah, yo)", "\n", "It's you and me", "\n", "It's you and me, won't be unhappy (Yeah, yeah, yo)", "\n", "[Bridge]", "\n", "Oh, come on, baby (Yeah)", "\n", "Oh, come on, darlin' (Yo)", "\n", "Let me steal this moment from you now", "\n", "Oh, come on, angel", "\n", "Come on, come on, darlin'", "\n", "Let's exchange the experience (Yo, ooh, ooh)", "\n", "\n", "[Chorus]", "\n", {:annotation_id=>2970368, :text=>["And if I only could", "\n", "I'd make a deal with God", "\n", "And I'd get him to swap our places", "\n", "I'd be runnin' up that road", "\n", "Be runnin' up that hill", "\n", "With no problems", "\n", "Say, if I only could", "\n", "I'd make a deal with God", "\n", "And I'd get him to swap our places", "\n", "I'd be runnin' up that road", "\n", "Be runnin' up that hill", "\n", "With no problems", "\n", "Say, if I only could", "\n", "I'd make a deal with God", "\n", "And I'd get him to swap our places", "\n", "I'd be runnin' up that road", "\n", "Be runnin' up that hill", "\n", "With no problems"]}, "\n", "[Outro]", "\n", {:annotation_id=>2970368, :text=>["Say, if I only could", "\n", "I'd be runnin' up that hill", "\n", "With no problems", "\n", "(If I only could, be runnin' up that hill)", "\n", "(If I only could, be runnin' up that hill)"]}]}}
        end

        def tags_data
          {:track=>{:tags=>[{:name=>"Adult Alternative"}, {:name=>"Brit Pop"}, {:name=>"Eighties"}, {:name=>"British Rock"}, {:name=>"UK"}, {:name=>"Rock"}, {:name=>"Synth-Pop"}, {:name=>"Pop"}, {:name=>"New Wave"}, {:name=>"Art Pop"}]}}
        end
      end
    end
  end
end
