require:
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'spec/helpers/**/*'
    - 'spec/spec_helper.rb'
    - 'Gemfile'
    - 'Rakefile'

Layout/LineLength:
  Max: 80
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'app/decorators/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*.rb'
    - 'app/models/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/decorators/**/*.rb'

Metrics/ParameterLists:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: 'space'
