module Helpers
  module Bandcamp
    class << self
      def search_data
        {:search=>{:albums=>[{:link=>"https://wildnothingct.bandcamp.com/album/indigo", :title=>"Indigo | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/live-from-brooklyn-steel", :title=>"Live From Brooklyn Steel | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/laughing-gas-ep", :title=>"Laughing Gas EP | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/golden-haze", :title=>"Golden Haze | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/blue-wings", :title=>"Blue Wings | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/life-of-pause", :title=>"Life of Pause | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/letting-go", :title=>"Letting Go | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/empty-estate", :title=>"Empty Estate | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/nocturne", :title=>"Nocturne | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/bend", :title=>"Bend | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/wheel-of-misfortune", :title=>"Wheel of Misfortune | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/dizziness", :title=>"Dizziness | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/canyon-on-fire", :title=>"Canyon on Fire | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/nocturne", :title=>"Nocturne | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/gemini", :title=>"Gemini | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/the-world-is-a-hungry-place", :title=>"The World Is a Hungry Place | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/shadow", :title=>"Shadow | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/alien", :title=>"Alien | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/bored-games", :title=>"Bored Games | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/only-heather", :title=>"Only Heather | Wild Nothing"}], :page=>1}}
      end
    end
  end
end
