module Helpers
  module Bing
    class << self
      def search_data
        {:search=>{:page=>1, :results=>[{:description=>"Indigo by Wild Nothing, released 31 August 2018 1. Letting Go 2. Oscillation 3. Partners in Motion 4. Wheel of Misfortune 5. Shallow Water 6. Through Windows 7. The Closest Thing to Living 8. Dollhouse 9. Canyon on Fire 10. Flawed Translation 11. Bend Although civilization’s transition into a cyborg world seems inevitable, there are still those who recognize the beauty and power of a human ...", :link=>"https://wildnothingct.bandcamp.com/album/indigo", :title=>"Indigo | Wild Nothing"}, {:description=>"Laughing Gas EP by Wild Nothing, released 31 January 2020 1. Sleight of Hand 2. Dizziness 3. Foyer 4. Blue Wings 5. The World Is a Hungry Place On Laughing Gas, the third EP from Wild Nothing, songwriter and multi-instrumentalist Jack Tatum delves deeper into the territory where he thrives: namely, the synth and sophisti-pop of the 1980s.", :link=>"https://wildnothingct.bandcamp.com/album/laughing-gas-ep", :title=>"Laughing Gas EP | Wild Nothing"}, {:description=>"Buy Indigo Tour Video Store. T o u r. Follow Wild Nothing on Bandsintown / Songkick. V i d e o. Partners In Motion. Letting Go. To Know You / TV Queen. A Dancing Shell. Paradise. Follow Wild Nothing on Youtube. P h o t o. Follow Wild Nothing on Instagram. S i g n U p. SUBSCRIBE ...", :link=>"http://www.wildnothingmusic.com/", :title=>"Wild Nothing / Indigo"}, {:description=>"Wild Nothing by Moongazing Hare, released 04 January 2016 1. Slow Release 2. Wit's End 3. Wild Nothing 4. Dust On Your Breath 5. Some Beast 6. No Wild Things 7. The Grand Banks Empty 8. April's Fever 9. Into Poppy Fields 10. Just Can't Handle It 11. The Salmon Wives 12. True Comfort Moongazing Hare long in the tooth and chased by wild nothing through abundance and lack.", :link=>"https://moongazinghare.bandcamp.com/album/wild-nothing", :title=>"Wild Nothing | Moongazing Hare"}, {:description=>"8/30/2018 · Bandcamp / Buy “I’d rather ... Indigo takes Wild Nothing to places Tatum likely couldn’t have imagined from his Virginia Tech dorm. Whereas Gemini earned an honorary induction in …", :link=>"https://pitchfork.com/reviews/albums/wild-nothing-indigo/", :title=>"Wild Nothing: Indigo Album Review | Pitchfork"}]}}
      end
    end
  end
end
