module Helpers
  module Google
    class << self
      def search_data
        {:search=>{:page=>2, :results=>[{:description=>"6 track album", :image=>"https://f4.bcbits.com/img/a4171534853_16.jpg", :link=>"https://wildnothingct.bandcamp.com/album/golden-haze", :site_name=>"Wild Nothing", :title=>"Golden Haze, by Wild Nothing"}, {:description=>"12 track album", :image=>"https://f4.bcbits.com/img/a1315545409_5.jpg", :link=>"https://moongazinghare.bandcamp.com/album/wild-nothing", :site_name=>"Moongazing Hare", :title=>"Wild Nothing, by Moongazing Hare"}, {:description=>"3 track album", :image=>"https://f4.bcbits.com/img/a0509659330_5.jpg", :link=>"https://basinspectra.bandcamp.com/album/gemini-wild-nothing-ep", :site_name=>"Basin Spectra", :title=>"Gemini Wild Nothing EP, by Basin Spectra"}, {:description=>"4 track album", :image=>"https://f4.bcbits.com/img/a1261811385_5.jpg", :link=>"https://yumizouma.bandcamp.com/album/remix-ep", :site_name=>"Yumi Zouma", :title=>"Remix EP, by Yumi Zouma"}, {:description=>"1 track album", :image=>"https://f4.bcbits.com/img/a2799967513_5.jpg", :link=>"https://sfperkele.bandcamp.com/album/wild-nothing-2014", :site_name=>"SF Perkele", :title=>"Wild Nothing (2014), by SF Perkele"}, {:description=>"8 track album", :image=>"https://f4.bcbits.com/img/a3001996439_5.jpg", :link=>"https://mvnners.bandcamp.com/album/try-to-fall-asleep-without-her-demos", :site_name=>"mvnners", :title=>"try to fall asleep without her, demos, by mvnners"}, {:description=>"4 track album", :image=>"https://f4.bcbits.com/img/a3819592219_16.jpg", :link=>"https://beachvacation.bandcamp.com/album/maritime-ep", :site_name=>"Beach Vacation", :title=>"Maritime EP, by Beach Vacation"}, {:description=>"7 track album", :image=>"https://f4.bcbits.com/img/a0633133344_5.jpg", :link=>"https://windsmeasurerecordings.bandcamp.com/album/wild-horses-think-of-nothing-else-the-sea-tape-readings", :site_name=>"winds measure recordings", :title=>"wild horses think of nothing else the sea - tape readings, by patrick farmer"}, {:description=>"5 track album", :image=>"https://f4.bcbits.com/img/a3926807426_5.jpg", :link=>"https://vacantstarerecords.bandcamp.com/album/passing-glance-ep", :site_name=>"Vacant Stare Records", :title=>"Passing Glance EP, by TONER"}, {:description=>"4 track album", :image=>"https://f4.bcbits.com/img/a0801341544_5.jpg", :link=>"https://funeralparty.bandcamp.com/album/sparrows-tongue", :site_name=>"Funeral Party", :title=>"Sparrow's Tongue, by The Column"}], :total_pages=>10}}
      end
    end
  end
end
