module Helpers
  module Google
    class << self
      def search_data
        {:search=>{:page=>2, :results=>[{:image=>"https://f4.bcbits.com/img/a0102975203_5.jpg", :link=>"https://wildnothingct.bandcamp.com/album/empty-estate", :site_name=>"Wild Nothing", :title=>"Empty Estate, by Wild Nothing"}, {:image=>"https://f4.bcbits.com/img/a0301769417_5.jpg", :link=>"https://wildnothingct.bandcamp.com/track/life-of-pause", :site_name=>"Wild Nothing", :title=>"Life of Pause, by Wild Nothing"}, {:image=>"https://f4.bcbits.com/img/a3674503646_5.jpg", :link=>"https://capturedtracks.bandcamp.com/track/wild-nothing-a-womans-wisdom-demo", :site_name=>"Captured Tracks", :title=>"Wild Nothing - A Woman's Wisdom [Demo], by Captured Tracks"}, {:image=>"https://f4.bcbits.com/img/a4171534853_5.jpg", :link=>"https://wildnothingct.bandcamp.com/album/golden-haze", :site_name=>"Wild Nothing", :title=>"Golden Haze, by Wild Nothing"}, {:image=>"https://f4.bcbits.com/img/a0102975203_5.jpg", :link=>"https://wildnothingct.bandcamp.com/track/a-dancing-shell", :site_name=>"Wild Nothing", :title=>"A Dancing Shell, by Wild Nothing"}, {:image=>"https://f4.bcbits.com/img/a3600531791_5.jpg", :link=>"https://mollyburch.bandcamp.com/album/emotion", :site_name=>"Molly Burch", :title=>"Emotion, by Molly Burch"}, {:image=>"https://f4.bcbits.com/img/a1612004764_5.jpg", :link=>"https://wildnothingct.bandcamp.com/track/this-chain-wont-break", :site_name=>"Wild Nothing", :title=>"This Chain Won't Break, by Wild Nothing"}, {:image=>"https://f4.bcbits.com/img/a1040173735_5.jpg", :link=>"https://smallblack.bandcamp.com/track/boys-life-wild-nothing-remix", :site_name=>"Small Black", :title=>"Boys Life (Wild Nothing Remix), by Small Black"}, {:image=>"https://f4.bcbits.com/img/a4113642636_5.jpg", :link=>"https://wildnothingct.bandcamp.com/track/o-lilac", :site_name=>"Wild Nothing", :title=>"O Lilac, by Wild Nothing"}, {:image=>"https://f4.bcbits.com/img/a4121208730_5.jpg", :link=>"https://wildnothingct.bandcamp.com/track/nocturne-live-from-brooklyn-steel", :site_name=>"Wild Nothing", :title=>"Nocturne – Live From Brooklyn Steel, by Wild Nothing"}], :total_pages=>10}}
      end
    end
  end
end
