module Helpers
  module YouTube
    class << self
      def search_data
        {:search=>{:next_page=>"CAUQAA", :results=>[{:description=>"Provided to YouTube by BWSCD, Inc. Chinatown · Wild Nothing Gemini ℗ 2010 Captured Tracks Released on: 2010-05-25 Auto-generated by YouTube.", :preview=>"https://i.ytimg.com/vi/1aTIkQf3eRY/hqdefault.jpg", :title=>"Chinatown", :video_id=>"1aTIkQf3eRY"}, {:description=>"Lyrics: Innocent love, I need someone somewhere I need some way to come down I need some way to make things right Innocent love, I need someone ...", :preview=>"https://i.ytimg.com/vi/j6tZLVoAQnM/hqdefault.jpg", :title=>"Wild Nothing - Chinatown", :video_id=>"j6tZLVoAQnM"}, {:description=>"chinatown by wild nothing i do not own this song and no copyright infringement is intended.", :preview=>"https://i.ytimg.com/vi/n_H6sqpNAic/hqdefault.jpg", :title=>"Wild Nothing: Chinatown lyrics", :video_id=>"n_H6sqpNAic"}, {:description=>"Wild Nothing at Holocene in Portland, OR March 01, 2011 For photos from the show: http://www.qromag.com/concert_gallery/?g2_itemId=299539 for review: ...", :preview=>"https://i.ytimg.com/vi/DrR9BG9qkYI/hqdefault.jpg", :title=>"Wild Nothing &quot;Chinatown&quot; Live", :video_id=>"DrR9BG9qkYI"}, {:description=>"Provided to YouTube by BWSCD, Inc. Chinatown (Live from Brooklyn Steel) · Wild Nothing Live from Brooklyn Steel ℗ 2019 Captured Tracks Released on: ...", :preview=>"https://i.ytimg.com/vi/nRxvU-CZQgU/hqdefault.jpg", :title=>"Chinatown (Live from Brooklyn Steel)", :video_id=>"nRxvU-CZQgU"}]}}
      end
    end
  end
end
