# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/spotify/spotify.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/spotify/spotify.proto", :syntax => :proto3) do
    add_message "spotify_protobuf.BatchedEntityRequest" do
      optional :entity_request, :message, 2, "spotify_protobuf.BatchedEntityRequest.EntityRequest"
    end
    add_message "spotify_protobuf.BatchedEntityRequest.EntityRequest" do
      optional :entity_uri, :string, 1
      optional :query, :message, 2, "spotify_protobuf.BatchedEntityRequest.EntityRequest.ExtensionQuery"
    end
    add_message "spotify_protobuf.BatchedEntityRequest.EntityRequest.ExtensionQuery" do
      optional :extension_kind, :int32, 1
    end
    add_message "spotify_protobuf.BatchedExtensionResponse" do
      optional :extended_metadata, :message, 2, "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray"
    end
    add_message "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray" do
      optional :extension_data, :message, 3, "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData"
    end
    add_message "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData" do
      optional :header, :message, 1, "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData.EntityExtensionDataHeader"
      optional :extension_data, :message, 3, "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData.ExtensionData"
    end
    add_message "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData.EntityExtensionDataHeader" do
      optional :status_code, :int32, 1
    end
    add_message "spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData.ExtensionData" do
      optional :value, :bytes, 2
    end
    add_message "spotify_protobuf.Track" do
      proto3_optional :gid, :bytes, 1
      proto3_optional :name, :string, 2
      proto3_optional :album, :message, 3, "spotify_protobuf.Track.Album"
      repeated :artist, :message, 4, "spotify_protobuf.Track.Artist"
      repeated :restriction, :message, 11, "spotify_protobuf.Track.Restriction"
      repeated :file, :message, 12, "spotify_protobuf.Track.AudioFile"
      repeated :alternative, :message, 13, "spotify_protobuf.Track"
      repeated :preview, :message, 15, "spotify_protobuf.Track.AudioFile"
    end
    add_message "spotify_protobuf.Track.Album" do
      proto3_optional :name, :string, 2
      repeated :artist, :message, 3, "spotify_protobuf.Track.Artist"
    end
    add_message "spotify_protobuf.Track.Artist" do
      proto3_optional :name, :string, 2
    end
    add_message "spotify_protobuf.Track.Restriction" do
      oneof :country_restriction do
        optional :countries_allowed, :string, 2
        optional :countries_forbidden, :string, 3
      end
    end
    add_message "spotify_protobuf.Track.AudioFile" do
      proto3_optional :file_id, :bytes, 1
      proto3_optional :format, :enum, 2, "spotify_protobuf.Track.AudioFile.AudioFileFormat"
    end
    add_enum "spotify_protobuf.Track.AudioFile.AudioFileFormat" do
      value :OGG_VORBIS_96, 0
      value :OGG_VORBIS_160, 1
      value :OGG_VORBIS_320, 2
      value :MP3_256, 3
      value :MP3_320, 4
      value :MP3_160, 5
      value :MP3_96, 6
      value :MP3_160_ENC, 7
      value :AAC_24, 8
      value :AAC_48, 9
      value :FLAC_FLAC, 16
      value :FLAC_FLAC_24BIT, 22
    end
  end
end

module SpotifyProtobuf
  BatchedEntityRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedEntityRequest").msgclass
  BatchedEntityRequest::EntityRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedEntityRequest.EntityRequest").msgclass
  BatchedEntityRequest::EntityRequest::ExtensionQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedEntityRequest.EntityRequest.ExtensionQuery").msgclass
  BatchedExtensionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedExtensionResponse").msgclass
  BatchedExtensionResponse::EntityExtensionDataArray = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray").msgclass
  BatchedExtensionResponse::EntityExtensionDataArray::EntityExtensionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData").msgclass
  BatchedExtensionResponse::EntityExtensionDataArray::EntityExtensionData::EntityExtensionDataHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData.EntityExtensionDataHeader").msgclass
  BatchedExtensionResponse::EntityExtensionDataArray::EntityExtensionData::ExtensionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.BatchedExtensionResponse.EntityExtensionDataArray.EntityExtensionData.ExtensionData").msgclass
  Track = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.Track").msgclass
  Track::Album = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.Track.Album").msgclass
  Track::Artist = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.Track.Artist").msgclass
  Track::Restriction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.Track.Restriction").msgclass
  Track::AudioFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.Track.AudioFile").msgclass
  Track::AudioFile::AudioFileFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("spotify_protobuf.Track.AudioFile.AudioFileFormat").enummodule
end
