local:
  service: Disk
  root: <%= Rails.root.join('storage') %>
  public: true

cloudflare:
  service: S3
  endpoint: https://<%= Rails.application.credentials.dig(:storage, :account_id) %>.r2.cloudflarestorage.com
  access_key_id: <%= Rails.application.credentials.dig(:storage, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:storage, :secret_access_key) %>
  region: auto
  bucket: <%= Rails.application.credentials.dig(:storage, :bucket) %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>
