module Helpers
  module Discogs
    module Album
      class << self
        def info_data
          {:album=>{:artist=>"Kate Bush", :description=>"℗ 1985 Original Sound Recordings made by Novercia Ltd.© 1985 Novercia Ltd.\n© 1985 Kate Bush Music Publishing Ltd. / EMI.\n\nOn CD: \nMade in Japan\n\nSimilar version, but  WITHOUT PRICE CODE \"PM 516\" AND WITH \"MADE IN JAPAN\" ON BACK COVER.\n\n", :images=>{:extrasmall=>"https://img.discogs.com/eaRPicce1W5US9W1UGo5aukMbyA=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-16233996-1605730391-7184.jpeg.jpg", :large=>"https://img.discogs.com/eaRPicce1W5US9W1UGo5aukMbyA=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-16233996-1605730391-7184.jpeg.jpg", :medium=>"https://img.discogs.com/eaRPicce1W5US9W1UGo5aukMbyA=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-16233996-1605730391-7184.jpeg.jpg", :original=>"https://img.discogs.com/eaRPicce1W5US9W1UGo5aukMbyA=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-16233996-1605730391-7184.jpeg.jpg", :small=>"https://img.discogs.com/eaRPicce1W5US9W1UGo5aukMbyA=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-16233996-1605730391-7184.jpeg.jpg"}, :labels=>["EMI"], :released=>"1985", :source=>"discogs", :tags=>["Pop", "Pop Rock", "Ballad"], :title=>"Hounds Of Love", :tracks=>[{:id=>1, :length=>304, :title=>"Running Up That Hill (A Deal With God)"}, {:id=>2, :length=>183, :title=>"Hounds Of Love"}, {:id=>3, :length=>281, :title=>"The Big Sky"}, {:id=>4, :length=>189, :title=>"Mother Stands For Comfort"}, {:id=>5, :length=>310, :title=>"Cloudbusting"}, {:id=>6, :length=>166, :title=>"A Dream Of Sheep"}, {:id=>7, :length=>142, :title=>"Under Ice"}, {:id=>8, :length=>259, :title=>"Waking The Witch"}, {:id=>9, :length=>247, :title=>"Watching You Without Me"}, {:id=>10, :length=>244, :title=>"Jig Of Life"}, {:id=>11, :length=>373, :title=>"Hello Earth"}, {:id=>12, :length=>155, :title=>"The Morning Fog"}]}}
        end

        def info_multiple_artists_data
          {:album=>{:artist=>"Labrinth, Sia & Diplo Present LSD (53)", :description=>"Track 7, \"No New Friends\" is renamed as \"Know New Friends\" and the title on cover and inner sleeve does also have K and W in Know in different colour from the rest of the title, implying the initial No New Friends.\n\nPrinted inner sleeve.\n\nTrack order runs in a sequential manner on cover and on inner sleeve.", :images=>{:extrasmall=>"https://img.discogs.com/AHN5gi-unGimk9fqUXPajn_oTYw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13812684-1562432464-4174.jpeg.jpg", :large=>"https://img.discogs.com/AHN5gi-unGimk9fqUXPajn_oTYw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13812684-1562432464-4174.jpeg.jpg", :medium=>"https://img.discogs.com/AHN5gi-unGimk9fqUXPajn_oTYw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13812684-1562432464-4174.jpeg.jpg", :original=>"https://img.discogs.com/AHN5gi-unGimk9fqUXPajn_oTYw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13812684-1562432464-4174.jpeg.jpg", :small=>"https://img.discogs.com/AHN5gi-unGimk9fqUXPajn_oTYw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13812684-1562432464-4174.jpeg.jpg"}, :labels=>["Columbia", "Records (11)", "Mad Decent", "Monkey Puzzle Records", "Sony Music"], :released=>"28 Jun 2019", :source=>"discogs", :tags=>["Electronic", "Pop", "Synth-pop", "Dance-pop"], :title=>"LSD", :tracks=>[{:id=>1, :length=>116, :title=>"Welcome To The Wonderful World Of"}, {:id=>2, :length=>186, :title=>"Angel In Your Eyes"}, {:id=>3, :length=>213, :title=>"Genius"}, {:id=>4, :length=>204, :title=>"Audio"}, {:id=>5, :length=>187, :title=>"Thunderclouds"}, {:id=>6, :length=>194, :title=>"Mountains"}, {:id=>7, :length=>175, :title=>"Know New Friends"}, {:id=>8, :length=>195, :title=>"Heaven Can Wait"}, {:id=>9, :length=>209, :title=>"It's Time"}, {:id=>10, :length=>162, :title=>"Genius (Lil Wayne Remix)"}]}}
        end

        def info_different_artists_data
          {:album=>{:artist=>"Various", :description=>"Special Edition.\nOriginal Extended Versions\nTrack 13 is a Hidden Track With the \"I Love Disco Diamonds\" radio wedge (title take from cdtext)\n", :images=>{:extrasmall=>"", :large=>"", :medium=>"", :original=>"", :small=>""}, :labels=>["Blanco Y Negro (2)"], :released=>"2001", :source=>"discogs", :tags=>["Electronic", "Italo-Disco"], :title=>"I Love Disco Diamonds Collection Vol.  5", :tracks=>[{:artist=>"Michael Fortunati", :id=>1, :length=>315, :title=>"Into The Night (Slip And Slide)"}, {:artist=>"Silvio Pozzoli", :id=>2, :length=>330, :title=>"Step By Step"}, {:artist=>"Cliff Turner", :id=>3, :length=>372, :title=>"Moonlight Affair"}, {:artist=>"L'Affair", :id=>4, :length=>348, :title=>"Secret Eyes"}, {:artist=>"Ray (2)", :id=>5, :length=>315, :title=>"I'm Not A Dreamer"}, {:artist=>"Fred Ventura", :id=>6, :length=>335, :title=>"Leave Me Alone"}, {:artist=>"Closed", :id=>7, :length=>400, :title=>"Living In Your Eyes"}, {:artist=>"Brian And The Eden", :id=>8, :length=>369, :title=>"Celebration Tonight"}, {:artist=>"B.B. & Band", :id=>9, :length=>360, :title=>"Hold Me Tight"}, {:artist=>"Digital Emotion", :id=>10, :length=>513, :title=>"Go Go Yellow Screen"}, {:artist=>"Texas Johnny", :id=>11, :length=>414, :title=>"Superman"}, {:artist=>"Sphinx (2)", :id=>12, :length=>314, :title=>"Bad Girl"}, {:artist=>"No Artist", :id=>13, :length=>6, :title=>"I Love Disco Diamonds"}]}}
        end
      end
    end
  end
end
