module Helpers
  module LastFM
    module Album
      class << self
        def description_data
          {:album=>{:artist=>{:name=>"Wild Nothing"}, :description=>"Nocturne is the second studio album by American dream pop act Wild Nothing, released on August 28, 2012 on Captured Tracks.\n\nThe success of Wild Nothing's debut allowed Jack Tatum to record in a full studio for its follow-up, a change of pace from Gemini's exclusive use of the laptop for recording. Working with producer Nicolas Vernhes, Tatum stated: “The biggest thing was just having a producer, having somebody extremely knowledgeable to work with. I mean, obviously I had a lot of nice equipment at my disposal for the first time, too ... But I never wanted to use any of that to pursue a wholly different sound to the first album; it was just nice to have somebody to bounce ideas off, to help me tweak things.” \"Shadow,\" the first song from Nocturne to be released, features a string section, something Tatum \"never\" could have done without a studio environment", :title=>"Nocturne"}}
        end

        def info_data
          {:album=>{:artist=>{:name=>"Wild Nothing"}, :description=>"Nocturne is the second studio album by American dream pop act Wild Nothing, released on August 28, 2012 on Captured Tracks.\n\nThe success of Wild Nothing's debut allowed Jack Tatum to record in a full studio for its follow-up, a change of pace from Gemini's exclusive use of the laptop for recording. Working with producer Nicolas Vernhes, Tatum stated: “The biggest thing was just having a producer, having somebody extremely knowledgeable to work with. I...", :with_more=>{:description=>true, :tags=>true}, :id=>1, :image=>{:extrasmall=>"https://lastfm.freetls.fastly.net/i/u/64s/3601d7b9f23e43aea6f9fa002672c6eb.png", :large=>"https://lastfm.freetls.fastly.net/i/u/600x600/3601d7b9f23e43aea6f9fa002672c6eb.png", :medium=>"https://lastfm.freetls.fastly.net/i/u/300x300/3601d7b9f23e43aea6f9fa002672c6eb.png", :original=>"https://lastfm.freetls.fastly.net/i/u/3601d7b9f23e43aea6f9fa002672c6eb.png", :small=>"https://lastfm.freetls.fastly.net/i/u/174s/3601d7b9f23e43aea6f9fa002672c6eb.png"}, :listeners_count=>247670, :plays_count=>6178839, :source=>"lastfm", :tags=>[{:name=>"2012"}, {:name=>"dream pop"}, {:name=>"best of 2012"}, {:name=>"indie"}, {:name=>"favorite albums"}], :title=>"Nocturne", :tracks=>[{:artist=>{:name=>"Wild Nothing"}, :id=>1, :length=>258, :title=>"Shadow"}, {:artist=>{:name=>"Wild Nothing"}, :id=>2, :length=>185, :title=>"Midnight Song"}, {:artist=>{:name=>"Wild Nothing"}, :id=>3, :length=>318, :title=>"Nocturne"}, {:artist=>{:name=>"Wild Nothing"}, :id=>4, :length=>260, :title=>"Through the Grass"}, {:artist=>{:name=>"Wild Nothing"}, :id=>5, :length=>200, :title=>"Only Heather"}, {:artist=>{:name=>"Wild Nothing"}, :id=>6, :length=>218, :title=>"This Chain Won’t Break"}, {:artist=>{:name=>"Wild Nothing"}, :id=>7, :length=>209, :title=>"Disappear Always"}, {:artist=>{:name=>"Wild Nothing"}, :id=>8, :length=>330, :title=>"Paradise"}, {:artist=>{:name=>"Wild Nothing"}, :id=>9, :length=>231, :title=>"Counting Days"}, {:artist=>{:name=>"Wild Nothing"}, :id=>10, :length=>207, :title=>"The Blue Dress"}, {:artist=>{:name=>"Wild Nothing"}, :id=>11, :length=>235, :title=>"Rheya"}]}}
        end

        def listeners_count_data
          {:album=>{:artist=>{:name=>"Wild Nothing"}, :listeners_count=>249779, :title=>"Nocturne"}}
        end

        def tags_data
          {:album=>{:artist=>{:name=>"Wild Nothing"}, :tags=>[{:name=>"2012", :percent=>100}, {:name=>"dream pop", :percent=>85}, {:name=>"best of 2012", :percent=>47}, {:name=>"indie", :percent=>39}, {:name=>"favorite albums", :percent=>39}, {:name=>"indie pop", :percent=>31}, {:name=>"indie rock", :percent=>24}, {:name=>"captured tracks", :percent=>24}, {:name=>"shoegaze", :percent=>16}, {:name=>"vinyl", :percent=>16}, {:name=>"chillout", :percent=>8}, {:name=>"rock", :percent=>8}, {:name=>"alternative", :percent=>8}, {:name=>"jangle pop", :percent=>8}, {:name=>"noise pop", :percent=>8}, {:name=>"chillwave", :percent=>8}, {:name=>"10s", :percent=>8}, {:name=>"favourite albums", :percent=>8}, {:name=>"lp", :percent=>8}, {:name=>"best albums ever", :percent=>8}, {:name=>"dream-pop", :percent=>8}, {:name=>"fucking incredible", :percent=>8}, {:name=>"bella union", :percent=>8}, {:name=>"chillgaze", :percent=>8}, {:name=>"albums I have on vinyl", :percent=>8}, {:name=>"rather good stuff", :percent=>8}, {:name=>"album of the month", :percent=>8}, {:name=>"pitchfork best new music", :percent=>8}, {:name=>"lapislazuli", :percent=>8}, {:name=>"best of the 2012", :percent=>8}, {:name=>"niemamnie", :percent=>8}], :title=>"Nocturne"}}
        end
      end
    end
  end
end
