module Helpers
  module LastFM
    module Common
      class << self
        def artist_tags_data
          {:tags=>{:artist=>"Wild Nothing", :tags=>[{:count=>100, :name=>"dream pop"}, {:count=>76, :name=>"shoegaze"}, {:count=>56, :name=>"indie pop"}, {:count=>45, :name=>"indie"}, {:count=>31, :name=>"seen live"}, {:count=>21, :name=>"tweegaze"}, {:count=>8, :name=>"Lo-Fi"}, {:count=>8, :name=>"american"}, {:count=>7, :name=>"chillwave"}, {:count=>4, :name=>"indie rock"}, {:count=>4, :name=>"pop"}, {:count=>4, :name=>"twee"}, {:count=>4, :name=>"alternative"}, {:count=>3, :name=>"new wave"}, {:count=>3, :name=>"electronic"}, {:count=>2, :name=>"twee pop"}, {:count=>2, :name=>"psychedelic"}, {:count=>2, :name=>"ambient"}, {:count=>2, :name=>"virginia"}, {:count=>2, :name=>"synthpop"}, {:count=>2, :name=>"jangle pop"}, {:count=>1, :name=>"rock"}, {:count=>1, :name=>"psychedelic pop"}, {:count=>1, :name=>"Dreamy"}, {:count=>1, :name=>"atmospheric"}, {:count=>1, :name=>"dream-pop"}, {:count=>1, :name=>"USA"}, {:count=>1, :name=>"Post-punk revival"}, {:count=>1, :name=>"hazy beach"}]}}
        end

        def album_tags_data
          {:tags=>{:album=>"Nocturne", :artist=>"Wild Nothing", :tags=>[{:count=>100, :name=>"2012"}, {:count=>85, :name=>"dream pop"}, {:count=>47, :name=>"best of 2012"}, {:count=>39, :name=>"indie"}, {:count=>39, :name=>"favorite albums"}, {:count=>31, :name=>"indie pop"}, {:count=>24, :name=>"indie rock"}, {:count=>24, :name=>"captured tracks"}, {:count=>16, :name=>"shoegaze"}, {:count=>16, :name=>"vinyl"}, {:count=>8, :name=>"chillout"}, {:count=>8, :name=>"rock"}, {:count=>8, :name=>"alternative"}, {:count=>8, :name=>"jangle pop"}, {:count=>8, :name=>"noise pop"}, {:count=>8, :name=>"chillwave"}, {:count=>8, :name=>"10s"}, {:count=>8, :name=>"favourite albums"}, {:count=>8, :name=>"lp"}, {:count=>8, :name=>"best albums ever"}, {:count=>8, :name=>"dream-pop"}, {:count=>8, :name=>"fucking incredible"}, {:count=>8, :name=>"bella union"}, {:count=>8, :name=>"chillgaze"}, {:count=>8, :name=>"albums I have on vinyl"}, {:count=>8, :name=>"rather good stuff"}, {:count=>8, :name=>"album of the month"}, {:count=>8, :name=>"pitchfork best new music"}, {:count=>8, :name=>"lapislazuli"}, {:count=>8, :name=>"best of the 2012"}, {:count=>8, :name=>"niemamnie"}]}}
        end

        def track_tags_data
          {:tags=>{:artist=>"Wild Nothing", :tags=>[{:count=>100, :name=>"dream pop"}, {:count=>46, :name=>"indie"}, {:count=>46, :name=>"chillwave"}, {:count=>42, :name=>"shoegaze"}, {:count=>13, :name=>"electronica"}, {:count=>13, :name=>"indie pop"}, {:count=>13, :name=>"Mellow"}, {:count=>13, :name=>"best of 2010"}, {:count=>9, :name=>"indie rock"}, {:count=>9, :name=>"summer"}, {:count=>9, :name=>"light"}, {:count=>9, :name=>"cosmic currents"}, {:count=>5, :name=>"pop"}, {:count=>5, :name=>"80s"}, {:count=>5, :name=>"female vocalists"}, {:count=>5, :name=>"Love"}, {:count=>5, :name=>"Lo-Fi"}, {:count=>5, :name=>"new wave"}, {:count=>5, :name=>"Awesome"}, {:count=>5, :name=>"melodic"}, {:count=>5, :name=>"psychedelic"}, {:count=>5, :name=>"Dreamy"}, {:count=>5, :name=>"american"}, {:count=>5, :name=>"synthpop"}, {:count=>5, :name=>"nostalgic"}, {:count=>5, :name=>"I like"}, {:count=>5, :name=>"modern rock"}, {:count=>5, :name=>"female vocalist"}, {:count=>5, :name=>"Ballad"}, {:count=>5, :name=>"lovely"}, {:count=>5, :name=>"sunny"}, {:count=>5, :name=>"sweet"}, {:count=>5, :name=>"checkout"}, {:count=>5, :name=>"Neo-Psychedelia"}, {:count=>5, :name=>"Dream"}, {:count=>5, :name=>"sex music"}, {:count=>5, :name=>"bright"}, {:count=>5, :name=>"bedroom pop"}, {:count=>5, :name=>"lizvelrene2010"}, {:count=>5, :name=>"campfire songs"}, {:count=>5, :name=>"my 10s"}, {:count=>5, :name=>"songs that i will still be listening to in a billion years"}, {:count=>5, :name=>"recs I like"}, {:count=>5, :name=>"austin radar"}, {:count=>5, :name=>"relaaax"}, {:count=>5, :name=>"elizabeth marie lester"}, {:count=>5, :name=>"see the world"}, {:count=>5, :name=>"rainy day with black smoke"}, {:count=>5, :name=>"flotsam"}, {:count=>5, :name=>"Shut Up And Drive"}, {:count=>5, :name=>"stone roses-like"}, {:count=>5, :name=>"local stuff from providence"}, {:count=>5, :name=>"Bellezza"}, {:count=>5, :name=>"geografia"}, {:count=>5, :name=>"ibero909fm"}, {:count=>5, :name=>"ibero909fm 8vo aniversario"}, {:count=>5, :name=>"La Ultima Estacion de Radio playlist"}, {:count=>5, :name=>"piuvicini"}, {:count=>5, :name=>"Quenovesquestoycontenta"}, {:count=>5, :name=>"3-4 indie"}, {:count=>5, :name=>"27oooo"}, {:count=>5, :name=>"mvt 2011"}, {:count=>5, :name=>"swirl beat"}, {:count=>5, :name=>"NO WAY TO NORWAY"}, {:count=>5, :name=>"dream pop not hypnagogic pop"}, {:count=>5, :name=>"inexplicable nostalgia"}, {:count=>5, :name=>"song of 2015"}, {:count=>5, :name=>"to all the boys ive loved before"}], :track=>"Chinatown"}}
        end
      end
    end
  end
end
