module Helpers
  module LastFM
    module Common
      class << self
        def artist_tags_data
          {:artist=>{:name=>"Wild Nothing", :tags=>[{:name=>"dream pop", :percent=>100}, {:name=>"shoegaze", :percent=>76}, {:name=>"indie pop", :percent=>56}, {:name=>"indie", :percent=>45}, {:name=>"seen live", :percent=>31}, {:name=>"tweegaze", :percent=>21}, {:name=>"Lo-Fi", :percent=>8}, {:name=>"american", :percent=>8}, {:name=>"chillwave", :percent=>7}, {:name=>"indie rock", :percent=>4}, {:name=>"pop", :percent=>4}, {:name=>"twee", :percent=>4}, {:name=>"alternative", :percent=>4}, {:name=>"new wave", :percent=>3}, {:name=>"electronic", :percent=>3}, {:name=>"twee pop", :percent=>2}, {:name=>"psychedelic", :percent=>2}, {:name=>"ambient", :percent=>2}, {:name=>"virginia", :percent=>2}, {:name=>"synthpop", :percent=>2}, {:name=>"jangle pop", :percent=>2}, {:name=>"rock", :percent=>1}, {:name=>"psychedelic pop", :percent=>1}, {:name=>"Dreamy", :percent=>1}, {:name=>"atmospheric", :percent=>1}, {:name=>"dream-pop", :percent=>1}, {:name=>"USA", :percent=>1}, {:name=>"Post-punk revival", :percent=>1}, {:name=>"hazy beach", :percent=>1}]}}
        end

        def album_tags_data
          {:album=>{:artist=>"Wild Nothing", :tags=>[{:name=>"2012", :percent=>100}, {:name=>"dream pop", :percent=>85}, {:name=>"best of 2012", :percent=>47}, {:name=>"indie", :percent=>39}, {:name=>"favorite albums", :percent=>39}, {:name=>"indie pop", :percent=>31}, {:name=>"indie rock", :percent=>24}, {:name=>"captured tracks", :percent=>24}, {:name=>"shoegaze", :percent=>16}, {:name=>"vinyl", :percent=>16}, {:name=>"chillout", :percent=>8}, {:name=>"rock", :percent=>8}, {:name=>"alternative", :percent=>8}, {:name=>"jangle pop", :percent=>8}, {:name=>"noise pop", :percent=>8}, {:name=>"chillwave", :percent=>8}, {:name=>"10s", :percent=>8}, {:name=>"favourite albums", :percent=>8}, {:name=>"lp", :percent=>8}, {:name=>"best albums ever", :percent=>8}, {:name=>"dream-pop", :percent=>8}, {:name=>"fucking incredible", :percent=>8}, {:name=>"bella union", :percent=>8}, {:name=>"chillgaze", :percent=>8}, {:name=>"albums I have on vinyl", :percent=>8}, {:name=>"rather good stuff", :percent=>8}, {:name=>"album of the month", :percent=>8}, {:name=>"pitchfork best new music", :percent=>8}, {:name=>"lapislazuli", :percent=>8}, {:name=>"best of the 2012", :percent=>8}, {:name=>"niemamnie", :percent=>8}], :title=>"Nocturne"}}
        end

        def track_tags_data
          {:track=>{:artist=>"Wild Nothing", :tags=>[{:name=>"dream pop", :percent=>100}, {:name=>"indie", :percent=>46}, {:name=>"chillwave", :percent=>46}, {:name=>"shoegaze", :percent=>42}, {:name=>"electronica", :percent=>13}, {:name=>"indie pop", :percent=>13}, {:name=>"Mellow", :percent=>13}, {:name=>"best of 2010", :percent=>13}, {:name=>"indie rock", :percent=>9}, {:name=>"summer", :percent=>9}, {:name=>"light", :percent=>9}, {:name=>"cosmic currents", :percent=>9}, {:name=>"pop", :percent=>5}, {:name=>"80s", :percent=>5}, {:name=>"female vocalists", :percent=>5}, {:name=>"Love", :percent=>5}, {:name=>"Lo-Fi", :percent=>5}, {:name=>"new wave", :percent=>5}, {:name=>"Awesome", :percent=>5}, {:name=>"melodic", :percent=>5}, {:name=>"psychedelic", :percent=>5}, {:name=>"Dreamy", :percent=>5}, {:name=>"american", :percent=>5}, {:name=>"synthpop", :percent=>5}, {:name=>"nostalgic", :percent=>5}, {:name=>"I like", :percent=>5}, {:name=>"modern rock", :percent=>5}, {:name=>"female vocalist", :percent=>5}, {:name=>"Ballad", :percent=>5}, {:name=>"lovely", :percent=>5}, {:name=>"sunny", :percent=>5}, {:name=>"sweet", :percent=>5}, {:name=>"checkout", :percent=>5}, {:name=>"Neo-Psychedelia", :percent=>5}, {:name=>"Dream", :percent=>5}, {:name=>"sex music", :percent=>5}, {:name=>"bright", :percent=>5}, {:name=>"bedroom pop", :percent=>5}, {:name=>"lizvelrene2010", :percent=>5}, {:name=>"campfire songs", :percent=>5}, {:name=>"my 10s", :percent=>5}, {:name=>"songs that i will still be listening to in a billion years", :percent=>5}, {:name=>"recs I like", :percent=>5}, {:name=>"austin radar", :percent=>5}, {:name=>"relaaax", :percent=>5}, {:name=>"elizabeth marie lester", :percent=>5}, {:name=>"see the world", :percent=>5}, {:name=>"rainy day with black smoke", :percent=>5}, {:name=>"flotsam", :percent=>5}, {:name=>"Shut Up And Drive", :percent=>5}, {:name=>"stone roses-like", :percent=>5}, {:name=>"local stuff from providence", :percent=>5}, {:name=>"Bellezza", :percent=>5}, {:name=>"geografia", :percent=>5}, {:name=>"ibero909fm", :percent=>5}, {:name=>"ibero909fm 8vo aniversario", :percent=>5}, {:name=>"La Ultima Estacion de Radio playlist", :percent=>5}, {:name=>"piuvicini", :percent=>5}, {:name=>"Quenovesquestoycontenta", :percent=>5}, {:name=>"3-4 indie", :percent=>5}, {:name=>"27oooo", :percent=>5}, {:name=>"mvt 2011", :percent=>5}, {:name=>"swirl beat", :percent=>5}, {:name=>"NO WAY TO NORWAY", :percent=>5}, {:name=>"dream pop not hypnagogic pop", :percent=>5}, {:name=>"inexplicable nostalgia", :percent=>5}, {:name=>"song of 2015", :percent=>5}, {:name=>"to all the boys ive loved before", :percent=>5}], :title=>"Chinatown"}}
        end
      end
    end
  end
end
