module Helpers
  module LastFM
    module Track
      class << self
        def description_data
          {:track=>{:artist=>{:name=>"Kate Bush"}, :description=>"\"Hounds of Love\" is a song written, produced and performed by British singer Kate Bush. It is the title track and the third single released from her number one 1985 album Hounds of Love. The single was released on 24 February 1986, and reached number 18 in the UK Singles Chart. \n\nThis is about the fear that rules all of us in one way or another, in particular the fear of love. The hounds of love that are hunting you is imagery for love itself as something to be feared, to run away from lest it catches you and rips you up. At the same time, it says that perhaps the hounds are friendly and one should not fear love (\"I've always been a coward, and never know what's good for me\"). (source songfacts).\n\nThe song was inspired in part by an old black-and-white movie which was sort of a cult classic in Kate's family titled Night Of The Demon. The movie was about demons who hid waiting in trees - the song's opening line (in a male voice) \"It's coming! It's in the trees!\" is taken directly from the movie.\n\nIn October 2004, Q magazine placed this song at No.21 in its list of the 50 greatest British songs of all-time. \n\nBritish band The Futureheads covered the song in 2005, scoring a UK top 10 hit with it.", :title=>"Hounds of Love"}}
        end

        def info_data
          {:track=>{:album=>{:title=>"Hounds of Love"}, :artist=>{:name=>"Kate Bush"}, :description=>"\"Hounds of Love\" is a song written, produced and performed by British singer Kate Bush. It is the title track and the third single released from her number one 1985 album Hounds of Love. The single was released on 24 February 1986, and reached number 18 in the UK Singles Chart. \n\nThis is about the fear that rules all of us in one way or another, in particular the fear of love. The hounds of...", :with_more=>{:description=>true, :tags=>true}, :id=>1, :image=>{:extrasmall=>"https://lastfm.freetls.fastly.net/i/u/64s/391be121643ab50801b7955b0ac5b50c.png", :large=>"https://lastfm.freetls.fastly.net/i/u/600x600/391be121643ab50801b7955b0ac5b50c.png", :medium=>"https://lastfm.freetls.fastly.net/i/u/300x300/391be121643ab50801b7955b0ac5b50c.png", :original=>"https://lastfm.freetls.fastly.net/i/u/391be121643ab50801b7955b0ac5b50c.png", :small=>"https://lastfm.freetls.fastly.net/i/u/174s/391be121643ab50801b7955b0ac5b50c.png"}, :length=>182, :listeners_count=>279845, :plays_count=>1839646, :tags=>[{:name=>"80s"}, {:name=>"female vocalists"}, {:name=>"pop"}, {:name=>"alternative"}, {:name=>"singer-songwriter"}], :title=>"Hounds of Love"}}
        end

        def similar_data
          {:track=>{:artist=>{:name=>"Wild Nothing"}, :page=>2, :similar=>[{:artist=>{:name=>"Craft Spells"}, :id=>1, :length=>240, :title=>"After the Moment"}, {:artist=>{:name=>"DIIV"}, :id=>2, :length=>185, :title=>"Sometime"}, {:artist=>{:name=>"Beach Fossils"}, :id=>3, :length=>201, :title=>"Shallow"}, {:artist=>{:name=>"Beach House"}, :id=>4, :length=>0, :title=>"Space Song"}, {:artist=>{:name=>"Chapterhouse"}, :id=>5, :length=>303, :title=>"Pearl"}], :title=>"chinatown", :total_pages=>40}}
        end

        def tags_data
          {:track=>{:artist=>{:name=>"Wild Nothing"}, :tags=>[{:name=>"dream pop"}, {:name=>"indie"}, {:name=>"chillwave"}, {:name=>"shoegaze"}, {:name=>"electronica"}, {:name=>"indie pop"}, {:name=>"Mellow"}, {:name=>"best of 2010"}, {:name=>"indie rock"}, {:name=>"summer"}, {:name=>"light"}, {:name=>"cosmic currents"}, {:name=>"pop"}, {:name=>"80s"}, {:name=>"female vocalists"}, {:name=>"Love"}, {:name=>"Lo-Fi"}, {:name=>"new wave"}, {:name=>"Awesome"}, {:name=>"melodic"}, {:name=>"psychedelic"}, {:name=>"Dreamy"}, {:name=>"american"}, {:name=>"synthpop"}, {:name=>"nostalgic"}, {:name=>"I like"}, {:name=>"modern rock"}, {:name=>"female vocalist"}, {:name=>"Ballad"}, {:name=>"lovely"}, {:name=>"sunny"}, {:name=>"sweet"}, {:name=>"checkout"}, {:name=>"Neo-Psychedelia"}, {:name=>"Dream"}, {:name=>"sex music"}, {:name=>"bright"}, {:name=>"bedroom pop"}, {:name=>"lizvelrene2010"}, {:name=>"campfire songs"}, {:name=>"my 10s"}, {:name=>"songs that i will still be listening to in a billion years"}, {:name=>"recs I like"}, {:name=>"austin radar"}, {:name=>"relaaax"}, {:name=>"elizabeth marie lester"}, {:name=>"see the world"}, {:name=>"rainy day with black smoke"}, {:name=>"flotsam"}, {:name=>"Shut Up And Drive"}, {:name=>"stone roses-like"}, {:name=>"local stuff from providence"}, {:name=>"Bellezza"}, {:name=>"geografia"}, {:name=>"ibero909fm"}, {:name=>"ibero909fm 8vo aniversario"}, {:name=>"La Ultima Estacion de Radio playlist"}, {:name=>"piuvicini"}, {:name=>"Quenovesquestoycontenta"}, {:name=>"3-4 indie"}, {:name=>"27oooo"}, {:name=>"mvt 2011"}, {:name=>"swirl beat"}, {:name=>"NO WAY TO NORWAY"}, {:name=>"dream pop not hypnagogic pop"}, {:name=>"inexplicable nostalgia"}, {:name=>"song of 2015"}, {:name=>"to all the boys ive loved before"}], :title=>"Chinatown"}}
        end
      end
    end
  end
end
