module Helpers
  module YouTube
    module Channel
      class << self
        def videos_data
          {:channel=>{:next_page=>"CAoQAA", :title=>"Shake80sFrenchMusic", :videos=>[{:image=>{:extrasmall=>"https://i.ytimg.com/vi/Iok4LyzJRh8/default.jpg", :large=>"https://i.ytimg.com/vi/Iok4LyzJRh8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/Iok4LyzJRh8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/Iok4LyzJRh8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/Iok4LyzJRh8/mqdefault.jpg"}, :publish_date=>"09 Sep 2018", :title=>"Alexis Zad - Petit bonhomme - 1987 (Maxi)", :youtube_id=>"Iok4LyzJRh8"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/jHmHfMuOHfs/default.jpg", :large=>"https://i.ytimg.com/vi/jHmHfMuOHfs/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/jHmHfMuOHfs/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/jHmHfMuOHfs/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/jHmHfMuOHfs/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :title=>"1999 - Ca faisait si longtemps - 1987 (mix version courte)", :youtube_id=>"jHmHfMuOHfs"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/qw0SDnhNmW4/default.jpg", :large=>"https://i.ytimg.com/vi/qw0SDnhNmW4/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/qw0SDnhNmW4/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/qw0SDnhNmW4/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/qw0SDnhNmW4/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :title=>"1999 - Ca faisait si longtemps - 1987 (Space mix)", :youtube_id=>"qw0SDnhNmW4"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/veJojiNq6cM/default.jpg", :large=>"https://i.ytimg.com/vi/veJojiNq6cM/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/veJojiNq6cM/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/veJojiNq6cM/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/veJojiNq6cM/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :title=>"Cyril Morin - Metropolitan - 1987 (Face B)", :youtube_id=>"veJojiNq6cM"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/eP4yH-8IKH8/default.jpg", :large=>"https://i.ytimg.com/vi/eP4yH-8IKH8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/eP4yH-8IKH8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/eP4yH-8IKH8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/eP4yH-8IKH8/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :title=>"Cyril Morin - L'amour sauvage - 1987", :youtube_id=>"eP4yH-8IKH8"}]}}
        end
      end
    end
  end
end
