module Helpers
  module YouTube
    module Channel
      class << self
        def description_data
          {:channel=>{:description=>"Pitchfork.tv is dedicated to documenting independent music as it happens. Working with a veritable who’s who of independent artists, Pitchfork.tv has captured brilliant early performances, interviews, and documentaries with artists that would go on to become household names. With programming ranging from Exclusively Produced Music Videos, Short Films, Documentaries, Animation, Live Streaming Concerts / Festivals, and Episodic Series, Pitchfork TV is the destination for music lovers of all kinds."}}
        end

        def info_data
          {:channel=>{:created=>"2008-09-04", :description=>"Pitchfork.tv is dedicated to documenting independent music as it happens. Working with a veritable who’s who of independent artists, Pitchfork.tv has captured brilliant early performances, interviews, and documentaries with artists that would go on to become household names. With programming ranging from Exclusively Produced Music Videos, Short Films, Documentaries, Animation, Live Streaming Co...", :image=>{:extrasmall=>"https://yt3.ggpht.com/ytc/AKedOLT9FoTw4_JHsDA3FZ9CLii_Y-pz625tTdRUP-kM2g=s50-c-k-c0x00ffffff-no-rj", :large=>"https://yt3.ggpht.com/ytc/AKedOLT9FoTw4_JHsDA3FZ9CLii_Y-pz625tTdRUP-kM2g=s600-c-k-c0x00ffffff-no-rj", :medium=>"https://yt3.ggpht.com/ytc/AKedOLT9FoTw4_JHsDA3FZ9CLii_Y-pz625tTdRUP-kM2g=s300-c-k-c0x00ffffff-no-rj", :original=>"https://yt3.ggpht.com/ytc/AKedOLT9FoTw4_JHsDA3FZ9CLii_Y-pz625tTdRUP-kM2g=-c-k-c0x00ffffff-no-rj", :small=>"https://yt3.ggpht.com/ytc/AKedOLT9FoTw4_JHsDA3FZ9CLii_Y-pz625tTdRUP-kM2g=s100-c-k-c0x00ffffff-no-rj"}, :source=>{:id=>"UC7kI8WjpCfFoMSNDuRh_4lA", :name=>"youtube"}, :statistics=>{:subscribers_count=>1220000, :videos_count=>2715, :views_count=>502935103}, :title=>"Pitchfork", :with_more=>{:description=>true}}}          
        end

        def videos_data
          {:channel=>{:next_page=>"EAAaBlBUOkNBbw", :prev_page=>"EAEaBlBUOkNBVQ", :title=>"Shake80sFrenchMusic", :videos=>[{:image=>{:extrasmall=>"https://i.ytimg.com/vi/Iok4LyzJRh8/default.jpg", :large=>"https://i.ytimg.com/vi/Iok4LyzJRh8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/Iok4LyzJRh8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/Iok4LyzJRh8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/Iok4LyzJRh8/mqdefault.jpg"}, :publish_date=>"2018-09-09", :source=>{:id=>"Iok4LyzJRh8", :name=>"youtube"}, :title=>"Alexis Zad - Petit bonhomme - 1987 (Maxi)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/jHmHfMuOHfs/default.jpg", :large=>"https://i.ytimg.com/vi/jHmHfMuOHfs/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/jHmHfMuOHfs/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/jHmHfMuOHfs/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/jHmHfMuOHfs/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"jHmHfMuOHfs", :name=>"youtube"}, :title=>"1999 - Ca faisait si longtemps - 1987 (mix version courte)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/qw0SDnhNmW4/default.jpg", :large=>"https://i.ytimg.com/vi/qw0SDnhNmW4/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/qw0SDnhNmW4/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/qw0SDnhNmW4/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/qw0SDnhNmW4/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"qw0SDnhNmW4", :name=>"youtube"}, :title=>"1999 - Ca faisait si longtemps - 1987 (Space mix)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/veJojiNq6cM/default.jpg", :large=>"https://i.ytimg.com/vi/veJojiNq6cM/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/veJojiNq6cM/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/veJojiNq6cM/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/veJojiNq6cM/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"veJojiNq6cM", :name=>"youtube"}, :title=>"Cyril Morin - Metropolitan - 1987 (Face B)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/eP4yH-8IKH8/default.jpg", :large=>"https://i.ytimg.com/vi/eP4yH-8IKH8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/eP4yH-8IKH8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/eP4yH-8IKH8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/eP4yH-8IKH8/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"eP4yH-8IKH8", :name=>"youtube"}, :title=>"Cyril Morin - L'amour sauvage - 1987"}]}}
        end
      end
    end
  end
end
