module Helpers
  module YouTube
    module Playlist
      class << self
        def videos_data
          {:playlist=>{:next_page=>"CAoQAA", :prev_page=>"CAUQAQ", :videos=>[{:image=>{:extrasmall=>"https://i.ytimg.com/vi/Iok4LyzJRh8/default.jpg", :large=>"https://i.ytimg.com/vi/Iok4LyzJRh8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/Iok4LyzJRh8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/Iok4LyzJRh8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/Iok4LyzJRh8/mqdefault.jpg"}, :publish_date=>"09 Sep 2018", :source=>{:id=>"Iok4LyzJRh8", :name=>"youtube"}, :title=>"Alexis Zad - Petit bonhomme - 1987 (Maxi)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/jHmHfMuOHfs/default.jpg", :large=>"https://i.ytimg.com/vi/jHmHfMuOHfs/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/jHmHfMuOHfs/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/jHmHfMuOHfs/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/jHmHfMuOHfs/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :source=>{:id=>"jHmHfMuOHfs", :name=>"youtube"}, :title=>"1999 - Ca faisait si longtemps - 1987 (mix version courte)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/qw0SDnhNmW4/default.jpg", :large=>"https://i.ytimg.com/vi/qw0SDnhNmW4/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/qw0SDnhNmW4/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/qw0SDnhNmW4/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/qw0SDnhNmW4/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :source=>{:id=>"qw0SDnhNmW4", :name=>"youtube"}, :title=>"1999 - Ca faisait si longtemps - 1987 (Space mix)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/veJojiNq6cM/default.jpg", :large=>"https://i.ytimg.com/vi/veJojiNq6cM/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/veJojiNq6cM/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/veJojiNq6cM/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/veJojiNq6cM/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :source=>{:id=>"veJojiNq6cM", :name=>"youtube"}, :title=>"Cyril Morin - Metropolitan - 1987 (Face B)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/eP4yH-8IKH8/default.jpg", :large=>"https://i.ytimg.com/vi/eP4yH-8IKH8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/eP4yH-8IKH8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/eP4yH-8IKH8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/eP4yH-8IKH8/mqdefault.jpg"}, :publish_date=>"08 Sep 2018", :source=>{:id=>"eP4yH-8IKH8", :name=>"youtube"}, :title=>"Cyril Morin - L'amour sauvage - 1987"}]}}
        end
      end
    end
  end
end
