module Helpers
  module YouTube
    module Playlist
      class << self
        def info_data
          {:playlist=>{:channel=>{:source=>{:id=>"UC3I2GFN_F8WudD_2jUZbojA", :name=>"youtube"}, :title=>"KEXP"}, :description=>"Enter the world of the Black Constellation in preparation for KEXP’s upcoming podcast, Fresh off the Spaceship. The podcast will chart the influential artist collective’s path from a seed in our backyard in Seattle, Washington to an entity with cosmic reach. Black Constellation has encompassed such innovative and varied musical acts as Shabazz Palaces (helmed by Ishmael Butler of Grammy-award w...", :image=>{:extrasmall=>"https://i.ytimg.com/vi/-rJuYmxJtSs/default.jpg", :large=>"https://i.ytimg.com/vi/-rJuYmxJtSs/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/-rJuYmxJtSs/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/-rJuYmxJtSs/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/-rJuYmxJtSs/mqdefault.jpg"}, :publish_date=>"2022-02-23", :source=>{:id=>"PLUh4W61bt_K78wGbr6lUgPb5gjine4I6G", :name=>"youtube"}, :title=>"Fresh off the Spaceship: Enter the Black Constellation", :videos_count=>92, :with_more=>{:description=>true}}}
        end

        def description_data
          {:playlist=>{:description=>"Enter the world of the Black Constellation in preparation for KEXP’s upcoming podcast, Fresh off the Spaceship. The podcast will chart the influential artist collective’s path from a seed in our backyard in Seattle, Washington to an entity with cosmic reach. Black Constellation has encompassed such innovative and varied musical acts as Shabazz Palaces (helmed by Ishmael Butler of Grammy-award winning trio Digable Planets), Stas THEE Boss (formerly of THEESatisfaction), Erik Blood, OCnotes, Porter Ray, JusMoni, and Nicholas Galanin (Ya Tseen). It also includes visual and literary artists Maikoiyo Alley-Barnes and Nep Sidhu.\n\nHosted by KEXP’s Larry Mizell Jr. and Martin Douglas, each of the 10 episodes will take listeners on a musical journey connecting the stars of the Black Constellation and drawing meaning from their art, emphasizing the revolutionary power of communion along the way.\n\nFind out more: https://www.kexp.org/fresh-off-the-spaceship/\n\nSubscribe now wherever you get your podcasts:\n\nApple Podcasts \nhttps://apple.co/3hvidDZ\n\nStitcher \nhttps://bit.ly/3MgUGVl\n\nSpotify \nhttps://spoti.fi/3C9xPWU\n\nGoogle Podcasts \nhttps://bit.ly/3syXwgr\n\nAmazon Music \nhttps://amzn.to/3tojeD9\n\nPocket Casts \nhttps://bit.ly/3tr34c3\n\n\nPodcast cover art by Todd Westendorp.\n\nhttps://www.kexp.org/"}}          
        end

        def videos_data
          {:playlist=>{:channel=>{:source=>{:id=>"UCZBXFjbyp1gezLRsDbG2hKQ", :name=>"youtube"}, :title=>"Shake80sFrenchMusic"}, :next_page=>"EAAaBlBUOkNBbw", :prev_page=>"EAEaBlBUOkNBVQ", :source=>{:id=>"UUZBXFjbyp1gezLRsDbG2hKQ", :name=>"youtube"}, :title=>"Uploads from Shake80sFrenchMusic", :videos=>[{:image=>{:extrasmall=>"https://i.ytimg.com/vi/Iok4LyzJRh8/default.jpg", :large=>"https://i.ytimg.com/vi/Iok4LyzJRh8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/Iok4LyzJRh8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/Iok4LyzJRh8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/Iok4LyzJRh8/mqdefault.jpg"}, :publish_date=>"2018-09-09", :source=>{:id=>"Iok4LyzJRh8", :name=>"youtube"}, :title=>"Alexis Zad - Petit bonhomme - 1987 (Maxi)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/jHmHfMuOHfs/default.jpg", :large=>"https://i.ytimg.com/vi/jHmHfMuOHfs/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/jHmHfMuOHfs/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/jHmHfMuOHfs/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/jHmHfMuOHfs/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"jHmHfMuOHfs", :name=>"youtube"}, :title=>"1999 - Ca faisait si longtemps - 1987 (mix version courte)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/qw0SDnhNmW4/default.jpg", :large=>"https://i.ytimg.com/vi/qw0SDnhNmW4/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/qw0SDnhNmW4/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/qw0SDnhNmW4/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/qw0SDnhNmW4/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"qw0SDnhNmW4", :name=>"youtube"}, :title=>"1999 - Ca faisait si longtemps - 1987 (Space mix)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/veJojiNq6cM/default.jpg", :large=>"https://i.ytimg.com/vi/veJojiNq6cM/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/veJojiNq6cM/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/veJojiNq6cM/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/veJojiNq6cM/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"veJojiNq6cM", :name=>"youtube"}, :title=>"Cyril Morin - Metropolitan - 1987 (Face B)"}, {:image=>{:extrasmall=>"https://i.ytimg.com/vi/eP4yH-8IKH8/default.jpg", :large=>"https://i.ytimg.com/vi/eP4yH-8IKH8/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/eP4yH-8IKH8/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/eP4yH-8IKH8/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/eP4yH-8IKH8/mqdefault.jpg"}, :publish_date=>"2018-09-08", :source=>{:id=>"eP4yH-8IKH8", :name=>"youtube"}, :title=>"Cyril Morin - L'amour sauvage - 1987"}]}}
        end
      end
    end
  end
end
