module Helpers
  module YouTube
    module Search
      class << self
        def videos_data
          {:search=>{:next_page=>"CAoQAA", :prev_page=>"CAUQAQ", :videos=>[{:channel=>{:source=>{:id=>"UC7hfiDYRhlPwx6L3Daut6Qg", :name=>"youtube"}, :title=>"Photosphere"}, :image=>{:extrasmall=>"https://i.ytimg.com/vi/DrR9BG9qkYI/default.jpg", :large=>"https://i.ytimg.com/vi/DrR9BG9qkYI/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/DrR9BG9qkYI/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/DrR9BG9qkYI/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/DrR9BG9qkYI/mqdefault.jpg"}, :publish_date=>"2011-03-02", :source=>{:id=>"DrR9BG9qkYI", :name=>"youtube"}, :title=>"Wild Nothing \"Chinatown\" Live"}, {:channel=>{:source=>{:id=>"UCRuAlLXxTcpdZ75_DkbF2WA", :name=>"youtube"}, :title=>"Love & Music"}, :image=>{:extrasmall=>"https://i.ytimg.com/vi/c9bYZxEMkjI/default.jpg", :large=>"https://i.ytimg.com/vi/c9bYZxEMkjI/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/c9bYZxEMkjI/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/c9bYZxEMkjI/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/c9bYZxEMkjI/mqdefault.jpg"}, :publish_date=>"2019-09-18", :source=>{:id=>"c9bYZxEMkjI", :name=>"youtube"}, :title=>"Chinatown - Wild Nothing (To All the Boys I've Loved Before Soundtrack)"}, {:channel=>{:source=>{:id=>"UCfafc7eZJmMXgTH4ULud1Ow", :name=>"youtube"}, :title=>"shades of lyrics ›"}, :image=>{:extrasmall=>"https://i.ytimg.com/vi/J85aRP8matI/default.jpg", :large=>"https://i.ytimg.com/vi/J85aRP8matI/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/J85aRP8matI/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/J85aRP8matI/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/J85aRP8matI/mqdefault.jpg"}, :publish_date=>"2018-09-07", :source=>{:id=>"J85aRP8matI", :name=>"youtube"}, :title=>"Wild Nothing - Chinatown (Lyric video) • To All the Boys I've Loved Before Soundtrack •"}, {:channel=>{:source=>{:id=>"UC_2340gvw820T6FSVzfvsGQ", :name=>"youtube"}, :title=>"fauna.tv"}, :image=>{:extrasmall=>"https://i.ytimg.com/vi/v5txXg4nFNU/default.jpg", :large=>"https://i.ytimg.com/vi/v5txXg4nFNU/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/v5txXg4nFNU/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/v5txXg4nFNU/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/v5txXg4nFNU/mqdefault.jpg"}, :publish_date=>"2016-03-14", :source=>{:id=>"v5txXg4nFNU", :name=>"youtube"}, :title=>"Wild Nothing - Chinatown (Live in Chile)"}, {:channel=>{:source=>{:id=>"UC1eef0iQ2I-epAUGjVQMgYQ", :name=>"youtube"}, :title=>"Léa Shiny"}, :image=>{:extrasmall=>"https://i.ytimg.com/vi/--KQB1wkYYI/default.jpg", :large=>"https://i.ytimg.com/vi/--KQB1wkYYI/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/--KQB1wkYYI/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/--KQB1wkYYI/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/--KQB1wkYYI/mqdefault.jpg"}, :publish_date=>"2020-03-07", :source=>{:id=>"--KQB1wkYYI", :name=>"youtube"}, :title=>"wild nothing - chinatown (slowed)"}]}}
        end
      end
    end
  end
end
