module Helpers
  module YouTube
    module Video
      class << self
        def info_data
          {:video=>{:channel=>{:title=>"Wild Nothing - Topic", :youtube_id=>"UCbaJZUVqfEZPtwaUzGgdZ8A"}, :description=>"Provided to YouTube by BWSCD, Inc.\n\nChinatown · Wild Nothing\n\nGemini\n\n℗ 2010 Captured Tracks\n\nReleased on: 2010-05-25\n\nAuto-generated by YouTube.", :dislikes_count=>976, :image=>{:extrasmall=>"https://i.ytimg.com/vi/1aTIkQf3eRY/default.jpg", :large=>"https://i.ytimg.com/vi/1aTIkQf3eRY/sddefault.jpg", :medium=>"https://i.ytimg.com/vi/1aTIkQf3eRY/hqdefault.jpg", :original=>"https://i.ytimg.com/vi/1aTIkQf3eRY/maxresdefault.jpg", :small=>"https://i.ytimg.com/vi/1aTIkQf3eRY/mqdefault.jpg"}, :likes_count=>11029, :publish_date=>"01 Dec 2014", :tags=>[{:name=>"Wild"}, {:name=>"Nothing"}, {:name=>"Gemini"}, {:name=>"Chinatown"}], :title=>"Chinatown", :views_count=>578689, :with_more=>{:description=>false, :tags=>false}, :youtube_id=>"1aTIkQf3eRY"}}
        end

        def description_data
          {:video=>{:description=>"Provided to YouTube by BWSCD, Inc.\n\nChinatown · Wild Nothing\n\nGemini\n\n℗ 2010 Captured Tracks\n\nReleased on: 2010-05-25\n\nAuto-generated by YouTube."}}
        end

        def tags_data
          {:video=>{:tags=>[{:name=>"Wild"}, {:name=>"Nothing"}, {:name=>"Gemini"}, {:name=>"Chinatown"}]}}
        end
      end
    end
  end
end
