module Helpers
  module Bandcamp
    module Album
      class << self
        def description_data
          {:album=>{:artist=>"Wild Nothing", :description=>"Although civilization’s transition into a cyborg world seems inevitable, there are still those who recognize the beauty and power of a human touch to complement the circumvention. Jack Tatum understands this balance, and through a decade making music as Wild Nothing he has learned to embrace both sides of that dynamic—but perhaps never as distinctly as on Indigo, the fourth Wild Nothing album. On one hand, it is a return to the fresh, transcendent sweep of his debut, 2010’s Gemini, and on the other, a culmination of heights reached, paths traveled, and lessons learned while creating the follow-ups, Nocturne and Life of Pause. Indigo finds Tatum at his most efficient, calculated, and confident—resulting in an artful blend of hi-fi humanity and technology that fires on all circuits and synapses.", :title=>"Indigo"}}
        end

        def source_data
          {:album=>{:artist=>"Wild Nothing", :description=>"Although civilization’s transition into a cyborg world seems inevitable, there are still those who recognize the beauty and power of a human touch to complement the circumvention. Jack Tatum understands this balance, and through a decade making music as Wild Nothing he has learned to embrace both sides of that dynamic—but perhaps never as distinctly as on Indigo, the fourth Wild Nothing album. On one hand, it is a return to the fresh, transcendent sweep...", :images=>{:extrasmall=>"https://f4.bcbits.com/img/a3221996752_42.jpg", :large=>"https://f4.bcbits.com/img/a3221996752_5.jpg", :medium=>"https://f4.bcbits.com/img/a3221996752_4.jpg", :original=>"https://f4.bcbits.com/img/a3221996752_10.jpg", :small=>"https://f4.bcbits.com/img/a3221996752_3.jpg"}, :link=>"https://wildnothingct.bandcamp.com/album/indigo", :released=>"05 Jun 2018", :source=>"bandcamp", :tags=>["Rock", "indie", "indie pop", "Blacksburg"], :title=>"Indigo", :tracks=>[{:audio=>{:present=>true, :source=>"bandcamp"}, :id=>1, :length=>221, :link=>"https://wildnothingct.bandcamp.com/track/letting-go", :title=>"Letting Go"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>2, :length=>230, :link=>"https://wildnothingct.bandcamp.com/track/oscillation", :title=>"Oscillation"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>3, :length=>260, :link=>"https://wildnothingct.bandcamp.com/track/partners-in-motion", :title=>"Partners in Motion"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>4, :length=>255, :link=>"https://wildnothingct.bandcamp.com/track/wheel-of-misfortune", :title=>"Wheel of Misfortune"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>5, :length=>246, :link=>"https://wildnothingct.bandcamp.com/track/shallow-water", :title=>"Shallow Water"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>6, :length=>199, :link=>"https://wildnothingct.bandcamp.com/track/through-windows", :title=>"Through Windows"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>7, :length=>214, :link=>"https://wildnothingct.bandcamp.com/track/the-closest-thing-to-living", :title=>"The Closest Thing to Living"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>8, :length=>77, :link=>"https://wildnothingct.bandcamp.com/track/dollhouse", :title=>"Dollhouse"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>9, :length=>284, :link=>"https://wildnothingct.bandcamp.com/track/canyon-on-fire", :title=>"Canyon on Fire"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>10, :length=>238, :link=>"https://wildnothingct.bandcamp.com/track/flawed-translation", :title=>"Flawed Translation"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>11, :length=>245, :link=>"https://wildnothingct.bandcamp.com/track/bend", :title=>"Bend"}]}}
        end

        def redirect_data
          {:album=>{:artist=>"luxury elite", :description=>"We'll talk again soon.\r\n\r\nAR057\r\n\r\nfor more luxury elite check out:\r\nluxury-elite.tumblr.com\r\nluxuryelite.bandcamp.com\r\nsoundcloud.com/luxuryelite\r\nvk.com/luxuryelite\r\nwww.facebook.com/theluxuryelite\r\n\r\n'private' music video: \r\nhttp://www.youtube.com/watch?v=UaEPnyOBRds\r\n\r\nPreviously from Ailanthus Recordings:\r\nailanthusrecordings.bandcamp.com/album/i-ii\r\nailanthusrecordings.bandcamp.com/album/iii\r\nailanthusrecordings.bandcamp.com/album/split-lp\r\n\r\nhttp://fortune500.bandcamp.com/", :images=>{:extrasmall=>"https://f4.bcbits.com/img/a2256411068_42.jpg", :large=>"https://f4.bcbits.com/img/a2256411068_5.jpg", :medium=>"https://f4.bcbits.com/img/a2256411068_4.jpg", :original=>"https://f4.bcbits.com/img/a2256411068_10.jpg", :small=>"https://f4.bcbits.com/img/a2256411068_3.jpg"}, :link=>"https://ailanthusrecordings.bandcamp.com/album/blind-date", :released=>"19 Apr 2013", :source=>"bandcamp", :tags=>["Punk", "babewave", "blind date", "cruise", "eccojam"], :title=>"blind date", :tracks=>[{:audio=>{:present=>true, :source=>"bandcamp"}, :id=>1, :length=>195, :link=>"https://ailanthusrecordings.bandcamp.com/track/heartbeat", :title=>"heartbeat"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>2, :length=>160, :link=>"https://ailanthusrecordings.bandcamp.com/track/cold", :title=>"cold"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>3, :length=>258, :link=>"https://ailanthusrecordings.bandcamp.com/track/journey", :title=>"journey"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>4, :length=>106, :link=>"https://ailanthusrecordings.bandcamp.com/track/slideshow", :title=>"slideshow"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>5, :length=>152, :link=>"https://ailanthusrecordings.bandcamp.com/track/yacht-pop", :title=>"yacht pop"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>6, :length=>172, :link=>"https://ailanthusrecordings.bandcamp.com/track/socially", :title=>"socially"}, {:audio=>{:present=>true, :source=>"bandcamp"}, :id=>7, :length=>141, :link=>"https://ailanthusrecordings.bandcamp.com/track/private", :title=>"private"}]}}
        end

        def tags_data
          {:album=>{:artist=>"luxury elite", :tags=>["Soundtrack", "escapism", "late night lofi", "moonlit tv dinner", "vaporwave", "xerox fax machine's superheroes", "USA"], :title=>"high society"}}
        end
      end
    end
  end
end
