module Helpers
  module Bandcamp
    module Search
      class << self
        def albums_data
          {:search=>{:albums=>[{:link=>"https://wildnothingct.bandcamp.com/album/nocturne", :title=>"Nocturne | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/laughing-gas-ep", :title=>"Laughing Gas EP | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/live-from-brooklyn-steel", :title=>"Live From Brooklyn Steel | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/indigo", :title=>"Indigo | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/gemini", :title=>"Gemini | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/golden-haze", :title=>"Golden Haze | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/album/life-of-pause", :title=>"Life of Pause | Wild Nothing"}], :page=>1}}
        end

        def tracks_data
          {:search=>{:page=>1, :tracks=>[{:link=>"https://wildnothingct.bandcamp.com/track/nocturne", :title=>"Nocturne | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/nocturne-live-from-brooklyn-steel", :title=>"Nocturne – Live From Brooklyn Steel | Wild …"}, {:link=>"https://wildnothingct.bandcamp.com/track/shadow", :title=>"Shadow | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/the-world-is-a-hungry-place", :title=>"The World Is a Hungry Place | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/blue-wings", :title=>"Blue Wings | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/midnight-song", :title=>"Midnight Song | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/through-the-grass", :title=>"Through The Grass | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/blue-wings-2", :title=>"Blue Wings | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/counting-days", :title=>"Counting Days | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/alien", :title=>"Alien | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/letting-go", :title=>"Letting Go | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/oscillation", :title=>"Oscillation | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/bored-games", :title=>"Bored Games | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/wheel-of-misfortune", :title=>"Wheel of Misfortune | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/dizziness", :title=>"Dizziness | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/to-know-you", :title=>"To Know You | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/o-lilac", :title=>"O Lilac | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/partners-in-motion-live-from-brooklyn-steel?action=download", :title=>"Partners in Motion – Live From Brooklyn Steel | …"}, {:link=>"https://wildnothingct.bandcamp.com/track/foyer", :title=>"Foyer | Wild Nothing"}, {:link=>"https://wildnothingct.bandcamp.com/track/paradise-live-from-brooklyn-steel?action=download", :title=>"Paradise – Live From Brooklyn Steel | Wild Nothing"}]}}
        end
      end
    end
  end
end
